eureka:
  instance:
    hostname: discovery-service
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false
  zipkin:
    base-url: http://zipkin:9411
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus