spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/order
    username: andd
    password: pgAnDD1102
    
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.andd.ecommerce.kafka.OrderConfirmation

application:
  config:
    customer-url: http://gateway-service:8222/api/v1/customers
    payment-url: http://gateway-service:8222/api/v1/payments
    product-url: http://gateway-service:8222/api/v1/products
server:
  port: 8070