spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: discovery-service
eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/
